apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: layo084hq-go
  janus-idp.io/tekton: layo084hq-go
  backstage.io/kubernetes-id: layo084hq-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: layo084hq-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
