apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: layo084hq-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: layo084hq-go 
  name: layo084hq-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: layo084hq-go 
